### ISSUE TITLE
missing electronic diagram

### ISSUE THREAD

**Issue by benoit-girard** [arbalet-project/arbadoc#2]
the assembly_guidelines_arbalet_lack.pdf, page 8 (5C) refers to an electronic diagram that does not appear in the document.

**Comment by ymollard** [comment]
I must draw the circuit thanks to @fritzing ([Open source hardware program](http://fritzing.org)) but I'm really out of time at the moment, I have this [super fast draft](https://framapic.org/3RvLOqY8uyty/SCpS0hjv) on hand (The capacitor 20μF to 200μF or more, the resistor can be 100 Ω to 500 Ω).

I also accept PR for the Fritzing sketch ;)

**Comment by ymollard** [comment]
The Fritzing diagram is now available in step 6 of the [assembly guidelines](https://github.com/arbalet-project/arbadoc/blob/master/assembly_guidelines/lack/assembly_guidelines_arbalet_lack.pdf).
