### ISSUE TITLE
More precise specifications needed

### ISSUE THREAD

**Issue by benoit-girard** [arbalet-project/arbadoc#3]
If we do not want to order from pololu, more precise information about the requirements of the electronic parts are needed (specifications of the adapter, of the headers, etc.)

About the adapter: you recommend a 3A adapter on pololu, while your doc says that 5A are needed...

Et pour les utilisateurs français, qui ne voient pas trop l'intérêt d'acheter le matériel auprès d'un revendeur américain (beaucoup de transport pour rien), une traduction des noms de ces éléments permettrait de les trouver plus facilement sur les site web des revendeurs français...

**Comment by ymollard** [comment]
[I tried to detail more](https://github.com/arbalet-project/arbadoc/wiki/Build-your-own#supplies), let me know what you think and what information is still missing
3A was a typo, minimum is 5A per 150 LEDs.
I've also added the [French translation](https://github.com/arbalet-project/arbadoc/wiki/Build-your-own#french) to buy supplies at Leroy Merlin :) Most components can be found locally but for the strip It is waaaay cheaper to buy directly to Asian manufacturers however, so I advise ebay.

**Comment by benoit-girard** [comment]
Note that in the English description of the adapter, you provide a link to a 3A adapter on pololu. The risk is high that someone buys it following your recommendation and ends up with an underpowered system...

**Comment by benoit-girard** [comment]
OK, apparently, you changed that.
